server:
  port: 9001
spring:
  application:
    name: hrm-sysmanage
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_managesystem
      username: root
      password: 001026
mybatis-plus:
  mapper-locations: classpath:com/makaina/hrm/mapper/*Mapper.xml
  type-aliases-package: com.makaina.hrm.domain,com.makaina.hrm.query
